name: jellylinks-v10
services:
  jellyfin-v10:
    image: jellyfin/jellyfin:10.11.10
    container_name: jellylinks-v10
    volumes:
      - ./v10-config:/config
      - ./v10-cache:/cache
      - ./media:/media:ro
      - ./shows:/shows:ro
    ports:
      - 8098:8096
    restart: "no"
